sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  script:
    - ./script/build
    - npx semantic-release
  on:
    branch: master
