unit_test: &unit_test
  steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: install-dependencies
        command: yarn install
    - save_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules
    - run:
        name: tests
        command: 'yarn jest --ci'
        environment:
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
    - run:
        name: tslint
        command: 'yarn tslint --project . --format junit -o reports/junit/tslint-results.xml'
    - store_test_results:
        path: reports/junit
    - store_artifacts:
        path: reports/junit

version: 2
jobs:
  node-v6-latest:
    docker:
      - image: circleci/node:6
    <<: *unit_test
  node-v8-latest:
    docker:
      - image: circleci/node:8
    <<: *unit_test
  node-v10-latest:
    docker:
      - image: circleci/node:10
    <<: *unit_test
  node-v11-latest:
    docker:
      - image: circleci/node:11
    <<: *unit_test

workflows:
  version: 2
  test:
    jobs:
      - node-v6-latest
      - node-v8-latest
      - node-v10-latest
      - node-v11-latest
