aliases:
  install_dependencies_step: &install_dependencies_step
    run:
      name: install-dependencies
      command: yarn install

  unit_test: &unit_test
    steps:
      - checkout
      - *install_dependencies_step
      - run:
          name: tests
          command: 'yarn test:ci'
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - run:
          name: lint
          command: 'yarn lint'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

version: 2
jobs:
  node-v10-latest:
    docker:
      - image: circleci/node:10
    <<: *unit_test
  node-v12-latest:
    docker:
      - image: circleci/node:12
    <<: *unit_test
  node-v13-latest:
    docker:
      - image: circleci/node:13
    <<: *unit_test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *install_dependencies_step
      - run:
          name: Publish package
          command: npx semantic-release

workflows:
  version: 2
  test-deploy:
    jobs:
      - node-v10-latest
      - node-v12-latest
      - node-v13-latest
      - deploy:
          requires:
            - node-v10-latest
            - node-v12-latest
            - node-v13-latest
          filters:
            branches:
              only: master
